import { useCallback, useEffect, useState } from 'react';
import { inboxApi } from '../inbox/api';
import { RowsSkeleton } from '../inbox/Skeleton';
import s from '../../styles/AIAgent.module.css';
const tabs=['Knowledge Base','Services','Test Agent','Logs / Activity'];
const kinds={'Services':'service','Plans':'plan','Conversation Flows':'workflow','Knowledge Base':'knowledge','Responses':'response','Handoff Rules':'handoff'};
const types=['greeting','advertising','recommendation','requirements','ready_to_pay','request_invoice','request_account_number','payment_question','payment_sent','receipt_sent','payment_problem','human','knowledge','unknown'];
const common=[['title','Title'],['key','Unique key'],['category','Category'],['priority','Priority / display order','number'],['enabled','Enabled','checkbox'],['archived','Archived','checkbox']];
const fields={
 service:[['checkoutUrl','Course page URL'],['description','Description','textarea'],['platforms','Platforms (comma separated)','array'],['serviceType','Service type',['account_setup','ads_management','course']],['price','Price (NGN)','number'],['currency','Currency',['NGN']],['requirements','Secure onboarding instructions','textarea'],['workflow','Workflow'],['paymentEnabled','Allow invoices','checkbox'],['allowCustomBudget','Allow custom budgets','checkbox'],['minBudget','Minimum custom budget','number'],['maxBudget','Maximum custom budget','number']],
 plan:[['duration','Days','number'],['amount','Amount (NGN)','number'],['currency','Currency',['NGN']],['platforms','Platforms (comma separated)','array'],['service','Service key'],['description','Description','textarea']],
 knowledge:[['purpose','Purpose','textarea'],['intents','Customer intents (comma separated)'],['triggerExamples','Example customer messages','textarea'],['keywords','Keywords / phrases'],['semanticTrigger','Meaning to match','textarea'],['whenToUse','When to use','textarea'],['whenNotToUse','When not to use','textarea'],['requiredState','Required state','json'],['excludedState','Excluded state','json'],['preferredResponse','Preferred response','textarea'],['responseMode','Response mode',['STRICT','GUIDED','KNOWLEDGE']],['allowContext','Allow contextual wording','checkbox'],['facts','Approved facts','textarea'],['requiredQuestion','Required next question','textarea'],['nextObjective','Next objective',['ANSWER','DISCOVER_SERVICE','GET_SERVICE_TYPE','GET_PLATFORM','GET_BUDGET_DURATION','GET_BUDGET','GET_DURATION','SELECT_PLAN','CONFIRM_PROCEED','OFFER_PAYMENT_DETAILS','CHECK_PAYMENT','HANDOFF','COMPLETE']],['stateUpdates','State updates','json'],['paymentBehaviour','Payment-stage guidance','textarea'],['forceHandoff','Require human handoff','checkbox'],['handoffReason','Reason code'],['notes','Internal guidance','textarea'],['displayOrder','Display order','number']],
 tone:[['customer','Customer example','textarea'],['response','Preferred Joshspot reply','textarea']],
 response:[['description','Internal description','textarea'],['message','Message (supports {{variables}})','textarea'],['mode','Response mode',['STRICT','FLEXIBLE','INFORMATION']],['intent','Intent'],['workflow','Workflow'],['service','Service key'],['platform','Platform'],['variables','Variables (comma separated)','array'],['handoffAfterReply','Assign to CSS after this response','checkbox']],
 workflow:[['intent','Trigger intent',['advertising','*',...types.filter(i=>i!=='advertising')]],['serviceType','Service condition',['','account_setup','ads_management']],['field','State field',['selectedPlatform','serviceType','budget','duration','selectedService','recommendedPlan','currentStep']],['operator','Condition',['missing','equals','present']],['value','Condition value'],['response','Saved response key'],['options','Options (comma separated)','array'],['nextStep','Next step'],['action','Action',['reply','handoff']],['stateField','Update state field',['','selectedPlatform','serviceType','currentStep']],['stateValue','State value']],
 handoff:[['intent','Trigger intent',['*',...types]],['reason','Reason'],['team','Handoff team',['CSS','SS']],['agent','Specific staff ID (optional)'],['customerResponse','Customer-facing fallback','textarea']],
};
const configFields={
 'Identity & Tone':[['agentName','Agent name'],['displayName','Display name'],['role','Agent role'],['brand','Brand'],['greeting','Use greeting for generic hello','checkbox'],['tone','Tone/personality','textarea'],['writingStyle','Writing style','textarea'],['responseLength','Response length preference'],['emojiPreference','Emoji preference'],['language','Language behaviour'],['instructions','Additional system instructions','textarea'],['signature','Signature']],
 'Payments & Invoices':[['followupsEnabled','Enable pending-invoice reminders','checkbox'],['followupFirstHours','First reminder after hours','number'],['followupSecondHours','Second reminder after hours','number'],['followupMaximum','Maximum reminders (1–2)','number'],['invoicesEnabled','Enable invoice actions','checkbox'],['paymentTemplate','Verified payment message template','textarea']],
 'AI Settings':[['structuredSales','Use structured sales engine (enable in DRAFT first)','checkbox'],['paymentQuestionCooldownMinutes','Payment question cooldown (minutes)','number'],['enabled','Enabled','checkbox'],['mode','Rollout mode',['OFF','DRAFT','LIVE']],['autoReply','Allow automatic replies in LIVE','checkbox'],['provider','Provider',['openai']],['model','OpenAI model (or use backend OPENAI_MODEL)'],['confidence','Confidence threshold','number'],['maxResponseLength','Maximum reply characters','number'],['maxHistory','Recent messages included','number'],['debounceSeconds','Combine rapid messages for seconds','number'],['responseDelaySeconds','Reply delay (seconds)','number'],['maxConsecutive','Maximum AI turns (0 = unlimited)','number'],['maxDailyCalls','Daily model call limit (0 = unlimited)','number'],['maxConversationCalls','Daily call limit per conversation (0 = unlimited)','number'],['allowedIntents','Allowed intents','array'],['disallowedIntents','Disallowed intents','array'],['businessHoursEnabled','Use business hours','checkbox'],['timezone','Timezone'],['startHour','Opening hour (0–23)','number'],['endHour','Closing hour (1–24)','number'],['outsideHours','Outside hours',['handoff','continue']],['stickerAction','Stickers',['handoff','ignore']],['contactAction','Contact cards',['handoff','ignore']]],
};
const handoffFields=[['handoffTeam','Default team',['CSS','SS']],['fallbackAgent','Fallback staff ID'],['paymentAgent','Payment escalation staff ID'],['assignment','Assignment strategy',['least_loaded','round_robin','fallback']],['allowReturn','Staff can return conversations to AI','checkbox'],['fallbackResponse','Fallback message','textarea']];
function JsonInput({value,onChange}){const [text,setText]=useState(JSON.stringify(value||{},null,2));useEffect(()=>setText(JSON.stringify(value||{},null,2)),[value]);return <textarea rows={3} value={text} onChange={e=>{setText(e.target.value);try{const parsed=JSON.parse(e.target.value);e.target.setCustomValidity('');onChange(parsed);}catch{e.target.setCustomValidity('Enter a valid JSON object.');}}}/>;}
function Inputs({spec,value,onChange}){return spec.map(([key,label,type])=><label key={key} className={type==='checkbox'?s.check:undefined}><span>{label}</span>{type==='json'?<JsonInput value={value[key]} onChange={v=>onChange(key,v)}/>:Array.isArray(type)?<select value={value[key]??type[0]} onChange={e=>onChange(key,e.target.value)}>{type.map(v=><option key={v} value={v}>{v||'None'}</option>)}</select>:type==='textarea'?<textarea rows={4} value={value[key]||''} onChange={e=>onChange(key,e.target.value)} />:<input type={type==='checkbox'?'checkbox':type==='number'?'number':'text'} step={type==='number'?'any':undefined} checked={type==='checkbox'?Boolean(value[key]):undefined} value={type==='checkbox'?undefined:type==='array'?(value[key]||[]).join(', '):value[key]??''} onChange={e=>onChange(key,type==='checkbox'?e.target.checked:type==='number'?Number(e.target.value):type==='array'?e.target.value.split(',').map(v=>v.trim()):e.target.value)} />}</label>);}
function KnowledgeFields({value,onChange}){
 const groups={Triggering:['purpose','intents','triggerExamples','keywords','semanticTrigger','whenToUse','whenNotToUse','requiredState','excludedState'],Response:['preferredResponse','responseMode','allowContext'],Facts:['facts'], 'Next step':['requiredQuestion','nextObjective','stateUpdates'],Payment:['paymentBehaviour'],Handoff:['forceHandoff','handoffReason'],Notes:['notes','displayOrder']};
 return <div className={s.knowledgeGroups}>{Object.entries(groups).map(([name,keys])=><details key={name} open={name==='Response'} className={s.log}><summary>{name}</summary><div className={s.fields}><Inputs spec={fields.knowledge.filter(([key])=>keys.includes(key))} value={value} onChange={onChange}/></div></details>)}</div>;
}
function Records({kind,report}) {
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[category,setCategory]=useState(''),[enabled,setEnabled]=useState(''),[priority,setPriority]=useState(''),[next,setNext]=useState(null),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const load=useCallback(async(cursor)=>{setLoading(true);try{const r=await inboxApi(`/ai/records?${new URLSearchParams({kind,q,category,enabled,priority,...(cursor?{before:cursor}:{})})}`);setItems(old=>cursor?[...old,...r.items]:r.items);setNext(r.next);}catch(e){report(e.message);}finally{setLoading(false);}},[kind,q,category,enabled,priority,report]);
 useEffect(()=>{const t=setTimeout(()=>load(),250);return()=>clearTimeout(t);},[load]);
 const create=()=>{const data={};for(const[key,,type]of fields[kind])data[key]=Array.isArray(type)?type[0]:type==='array'?[]:type==='json'?{}:type==='checkbox'?false:type==='number'?0:'';if(kind==='knowledge')data.schemaVersion=1;setEditing({kind,title:'',key:'',category:'',priority:0,enabled:true,archived:false,data});};
 async function save(e){e.preventDefault();setBusy(true);try{await inboxApi(`/ai/records${editing._id?`/${editing._id}`:''}`,{method:editing._id?'PUT':'POST',body:editing});setEditing(null);await load();}catch(err){report(err.message);}finally{setBusy(false);}}
 return <section><div className={s.toolbar}><input placeholder="Search entries" aria-label="Search entries" value={q} onChange={e=>setQ(e.target.value)} /><input placeholder="Category" aria-label="Category filter" value={category} onChange={e=>setCategory(e.target.value)} /><select aria-label="Status filter" value={enabled} onChange={e=>setEnabled(e.target.value)}><option value="">All statuses</option><option value="true">Enabled</option><option value="false">Disabled</option></select><input type="number" aria-label="Priority filter" placeholder="Priority" value={priority} onChange={e=>setPriority(e.target.value)}/><button onClick={create}>Add {kind==='knowledge'?'knowledge':kind}</button></div>
 {editing?<form className={s.editor} onSubmit={save}><h3>{editing._id?'Edit':'New'} {kind}</h3><div className={s.fields}><Inputs spec={common} value={editing} onChange={(key,value)=>setEditing({...editing,[key]:value})}/>{kind==='knowledge'?<KnowledgeFields value={editing.data} onChange={(key,value)=>setEditing({...editing,data:{...editing.data,schemaVersion:1,[key]:value}})}/>:<Inputs spec={fields[kind]} value={editing.data} onChange={(key,value)=>setEditing({...editing,data:{...editing.data,[key]:value}})}/>}</div><footer>{editing._id&&<button type="button" onClick={()=>setEditing({...editing,_id:undefined,revision:undefined,key:editing.key+'_copy',title:editing.title+' (copy)',enabled:false})}>Duplicate</button>}<button type="button" onClick={()=>setEditing(null)}>Cancel</button><button disabled={busy}>{busy?'Saving…':'Save entry'}</button></footer></form>:<>{loading&&!items.length?<RowsSkeleton/>:<div className={s.entries}>{items.map(item=><button key={item._id} onClick={()=>setEditing(item.kind==='knowledge'?{...item,data:{...item.data,schemaVersion:1,preferredResponse:item.data.preferredResponse??item.data.answer??'',facts:item.data.facts??'',triggerExamples:item.data.triggerExamples??item.data.question??'',responseMode:item.data.responseMode||'KNOWLEDGE'}}:item)}><strong>{item.title}</strong>{item.kind==='service'&&<span>{item.data.serviceType==='ads_management'?'Calculator + recommended plans':`₦${Number(item.data.price).toLocaleString()}`}</span>}{item.kind==='plan'&&<span>{item.data.duration} days · ₦{Number(item.data.amount).toLocaleString()}</span>}<span>{item.category || item.kind} · Priority {item.priority} {item.kind==='knowledge'&&`· ${item.data.responseMode||'Legacy — review'}`}</span><small>{item.archived?'Archived':item.enabled?'Enabled':'Disabled'} · Updated {new Date(item.updatedAt).toLocaleDateString()}</small></button>)}</div>}{!loading&&!items.length&&<p>No entries yet.</p>}{next&&<button disabled={loading} onClick={()=>load(next)}>Load more</button>}</>}
 </section>;
}
function TestAgent({report}){
 const [text,setText]=useState(''),[type,setType]=useState('text'),[state,setState]=useState({}),[turns,setTurns]=useState([]),[verifiedPayment,setVerifiedPayment]=useState(false),[busy,setBusy]=useState(false);
 const send=async e=>{e.preventDefault();setBusy(true);try{const result=await inboxApi('/ai/test',{method:'POST',body:{text,type,state,verifiedPayment,structuredSales:true,history:turns.flatMap(t=>[{direction:'inbound',text:t.text},{direction:'outbound',text:t.result.response||''}])}});setState(result.state||{});setTurns(old=>[...old,{text,result}]);setText('');}catch(err){report(err.message);}finally{setBusy(false);}};
 return <section><p>Structured sales simulation. This never sends WhatsApp messages or creates payment accounts.</p><details className={s.log}><summary>Set test state</summary><label><input type="checkbox" checked={verifiedPayment} onChange={e=>setVerifiedPayment(e.target.checked)}/> Simulate backend-verified payment</label><JsonInput value={state} onChange={setState}/></details><div className={s.testTurns}>{turns.map((turn,i)=><article key={i}><b>{turn.text}</b><p>{turn.result.response || 'No reply'}</p><small>{turn.result.intent} · {turn.result.action} · Handoff: {turn.result.handoff || 'No'}</small><details><summary>State and decision</summary><pre>{JSON.stringify(turn.result,null,2)}</pre></details></article>)}</div><form className={s.testForm} onSubmit={send}><select aria-label="Simulated message type" value={type} onChange={e=>setType(e.target.value)}>{['text','image','audio','video','document','sticker','location'].map(v=><option key={v}>{v}</option>)}</select><textarea required aria-label="Test message" placeholder="Hi, I want you to run TikTok ads for me" value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy}>{busy?'Testing…':'Test message'}</button><button type="button" onClick={()=>{setTurns([]);setState({});setVerifiedPayment(false);}}>Reset conversation</button></form></section>;
}
function Logs({report}){
 const [items,setItems]=useState([]),[filters,setFilters]=useState({}),[next,setNext]=useState(null);
 const load=useCallback(async cursor=>{try{const r=await inboxApi(`/ai/logs?${new URLSearchParams({...filters,...(cursor?{before:cursor}:{})})}`);setItems(old=>cursor?[...old,...r.items]:r.items);setNext(r.next);}catch(e){report(e.message);}},[filters,report]);
 useEffect(()=>{const t=setTimeout(()=>load(),300);return()=>clearTimeout(t);},[load]);
 return <section><div className={s.toolbar}>{['q','conversation','intent','service','platform','stage','knowledge','handoff','action','from','to'].map(key=><input key={key} aria-label={`Filter ${key}`} type={['from','to'].includes(key)?'date':'text'} placeholder={key} value={filters[key]||''} onChange={e=>setFilters({...filters,[key]:e.target.value})}/>)}</div>{items.map(item=><details className={s.log} key={item._id}><summary>{new Date(item.createdAt).toLocaleString()} · {item.action || item.kind} {item.handoff && `· ${item.handoff}`}</summary><pre>{JSON.stringify(item,null,2)}</pre></details>)}{next&&<button onClick={()=>load(next)}>Load more activity</button>}</section>;
}
export default function AIAgent(){
 const [tab,setTab]=useState('Knowledge Base'),[config,setConfig]=useState(null),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[migration,setMigration]=useState(null);
 const load=useCallback(async()=>{try{const value=await inboxApi('/ai/config');setConfig(value);setData(value.data);}catch(e){setError(e.message);}},[]);
 useEffect(()=>{load();},[load]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await inboxApi('/ai/config',{method:'PUT',body:{revision:config.revision,data}});await load();setNotice('Settings saved');}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <div className={s.agent}><header className={s.heading}><div><small>{config?.data?.mode||'Loading'} · {config?.data?.structuredSales?'Structured sales':'Legacy engine'} · {config?.providerReady?'OpenAI configured':'OpenAI needs configuration'}</small></div><button onClick={()=>setSettingsOpen(!settingsOpen)} aria-expanded={settingsOpen}>Settings</button></header><nav className={s.tabs} aria-label="AI Agent sections">{tabs.map(name=><button key={name} aria-current={tab===name?'page':undefined} onClick={()=>{setTab(name);setError('');setNotice('');load();}}>{name}</button>)}</nav>{error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!config?<RowsSkeleton/>:config.revision<0?<section className={s.editor}><h2>Set up Joshspot Assistant</h2><p>Create the editable services, plans and responses from your specification. The agent starts in DRAFT mode.</p><button disabled={busy} onClick={async()=>{setBusy(true);try{await inboxApi('/ai/initialize',{method:'POST',body:{}});await load();}catch(e){setError(e.message);}finally{setBusy(false);}}}>Initialize in DRAFT</button></section>:<>
 {settingsOpen&&<section className={s.editor}><h3>Settings</h3><button onClick={async()=>{try{const value=await inboxApi('/ai/export');const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='joshspot-ai-config.json';a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}}}>Export configuration</button><form onSubmit={save}>{Object.entries({...configFields,'Handoff':handoffFields}).map(([name,spec])=><details key={name} className={s.log}><summary>{name}</summary><div className={s.fields}><Inputs spec={spec} value={data} onChange={(key,value)=>setData({...data,[key]:value})}/></div></details>)}<footer><button disabled={busy}>Save settings</button></footer></form><details className={s.log}><summary>Migration and legacy reference</summary><p>Preserve the existing configuration and add editable structured rules. This does not activate the new engine or change LIVE mode.</p><button onClick={async()=>{try{setMigration(await inboxApi('/ai/structured-migration'));}catch(e){setError(e.message);}}}>Preview migration</button>{migration&&<><pre>{JSON.stringify(migration,null,2)}</pre><button onClick={async()=>{try{await inboxApi('/ai/structured-migration',{method:'POST',body:{}});setNotice('Structured rules prepared. Review Knowledge Base, then test in DRAFT.');await load();}catch(e){setError(e.message);}}}>Prepare structured knowledge</button></>}<p><a href="/admin-7812er/ai-knowledge">Legacy knowledge document</a></p><details><summary>Legacy responses and workflows</summary><Records kind="response" report={setError}/><Records kind="workflow" report={setError}/></details></details></section>}
 {tab==='Knowledge Base'&&<p className={s.flow}>Discovery → Service → Platform → Qualification → Price → Proceed → Invoice → Payment → Fulfilment</p>}{kinds[tab]&&<Records key={kinds[tab]} kind={kinds[tab]} report={setError}/>}{tab==='Services'&&<details className={s.log}><summary>Recommended plans</summary><Records kind="plan" report={setError}/></details>}{tab==='Test Agent'&&<TestAgent report={setError}/>} {tab==='Logs / Activity'&&<Logs report={setError}/>}
 </>}</div>;
}
