import Head from "next/head";
import PublicLayout from "../components/PublicLayout";
import styles from "../styles/Privacy.module.css";

const sections = [
  ["information", "Information we handle", <><p>We collect information you provide when you contact Joshspot Media, enquire about a service, enrol in a course, or make a payment. This may include your name, phone number, email address, enquiry, course or service interest, and payment or invoice details.</p><p>Joshspot Inbox handles WhatsApp contact names and numbers, messages and attachments, message identifiers, timestamps and delivery/read statuses supplied through the WhatsApp Business Platform. Our team may add labels, assignments, internal notes, follow-up dates and relevant customer or payment records.</p><p>Our website may also collect referral links and campaign parameters, browser/device information, page visits and checkout events through cookies, local storage and advertising tools.</p></>],
  ["use", "How we use information", <><p>We use this information to respond to enquiries, deliver courses and services, process and reconcile payments, issue receipts, provide customer support, follow up on incomplete checkouts, and maintain conversation history. We also use operational information to secure our services, diagnose errors and measure marketing performance.</p><p>Authorised staff use Joshspot Inbox to manage conversations and customer relationships. Internal notes are for our team and are not sent as WhatsApp messages to customers.</p></>],
  ["providers", "Service providers and sharing", <><p>Information is processed by providers needed to operate these services, including Meta/WhatsApp for messaging, hosting and database providers for storage, payment providers for transactions, and email providers for notifications and receipts. These providers may process information outside your country.</p><p>Our website uses TikTok advertising tools, including browser pixel and server-side event reporting, to measure visits and conversions. Course-assistant questions may be sent to OpenAI to generate answers when that feature is enabled. Please avoid including sensitive information in course-assistant questions.</p><p>If you communicate through another connected support or automation service, that service may also process the conversation. Following links to Telegram, WhatsApp or other external platforms places you under those platforms’ privacy practices. We may disclose records where required by law or necessary to address fraud, security incidents or legal claims.</p></>],
  ["cookies", "Cookies and your choices", <><p>We use browser storage for website functionality and attribution, and advertising technologies to understand how visitors reach and use the site. You can manage cookies through your browser and advertising preferences through the relevant platform. Blocking storage or scripts may affect some website features.</p><p>You can ask us to stop promotional follow-ups by replying to a message or emailing us. Necessary responses about an existing service, payment or request may still be provided.</p></>],
  ["retention", "Storage, retention and security", <><p>Customer records and conversation history are stored in our business systems. Retention depends on the purpose of the record, ongoing support needs, payment and accounting obligations, and dispute or security requirements; there is no single automatic expiry period for all Inbox records.</p><p>Access to the CRM is restricted through authentication and staff permissions. We use safeguards to protect information, but no online system can guarantee absolute security. Please do not send passwords, payment PINs or full card details in a support conversation.</p></>],
  ["data-deletion", "Your information and deletion requests", <><p>To request access, correction or deletion of information held by Joshspot Media, email <a href="mailto:admin@joshspotmedia.com?subject=Privacy%20and%20data%20deletion%20request">admin@joshspotmedia.com</a> with the subject “Privacy and data deletion request”.</p><ol><li>Provide the name and phone number or email address you used to contact us.</li><li>Tell us what you would like accessed, corrected or deleted, including whether it relates to Joshspot Inbox / WhatsApp.</li><li>We may ask for limited information to verify that the records belong to you before acting on the request.</li></ol><p>We will review your request and explain the outcome or any records that need to be retained for legal, accounting, security or dispute purposes. Backup copies may remain until they are replaced under the relevant backup process. Deleting our records does not delete copies held independently by you, Meta/WhatsApp or another platform.</p></>],
  ["updates", "Updates and contact", <><p>This policy covers the Joshspot Media website, courses, services and Joshspot Inbox. We may update it as our services change; the date above identifies the latest revision.</p><p>For privacy questions, contact Joshspot Media at <a href="mailto:admin@joshspotmedia.com">admin@joshspotmedia.com</a>.</p></>],
];

export default function PrivacyPolicy() {
  return <PublicLayout>
    <Head><title>Privacy Policy | Joshspot Media</title><meta name="description" content="How Joshspot Media and Joshspot Inbox handle customer information, WhatsApp conversations and data deletion requests." /><link rel="canonical" href="https://joshspotmedia.com/privacy-policy" /></Head>
    <article className={styles.policy}>
      <header className={styles.hero}><span className={styles.eyebrow}>JOSHSPOT MEDIA · TRUST & PRIVACY</span><h1>Privacy policy</h1><p>Your conversations. Your information.<br />Here is how we handle them.</p><span className={styles.date}>Last updated: 3 October 2026</span></header>
      <div className={styles.layout}><nav className={styles.contents} aria-label="Privacy policy sections"><strong>On this page</strong>{sections.map(([id, title]) => <a key={id} href={`#${id}`}>{title}</a>)}<a className={styles.contact} href="mailto:admin@joshspotmedia.com">Contact us ↗</a></nav>
        <div className={styles.body}>{sections.map(([id, title, content], index) => <section key={id} id={id}><span className={styles.number}>{String(index + 1).padStart(2, "0")}</span><h2>{title}</h2>{content}</section>)}</div>
      </div>
    </article>
  </PublicLayout>;
}
