import { useEffect, useState } from 'react';
import { inboxApi } from './api';
import s from '../../styles/Inbox.module.css';
export default function AIControls({conversation,session,onUpdate,onError,detailsOnly=false}){
 const [busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[text,setText]=useState(''),[correction,setCorrection]=useState({});
 const ai=conversation.ai || {};const draft=ai.draft;const canControl=session.actor.admin || !conversation.assignedTo || conversation.assignedTo===session.actor.id;
 useEffect(()=>setCorrection({}),[conversation._id]);
 useEffect(()=>{setText(draft?.response||'');setEditing(false);},[draft?.inputId,draft?.response]);
 async function action(path,body,method='POST'){setBusy(true);try{await inboxApi(`/ai/conversations/${conversation._id}/${path}`,{method,body});await onUpdate();if(path==='state')setCorrection({});}catch(e){onError(e.message);}finally{setBusy(false);}}
 return <div className={s.aiControls}>
 {!detailsOnly&&<div><span>{ai.priority?'Payment · ':''}{ai.needsHuman?'Needs human':ai.active===false?'AI paused · Human handling':ai.state?'AI handling':'AI available'}</span>{canControl&&<button disabled={busy} onClick={()=>action('control',{action:ai.active===false?'return':'takeover'})}>{ai.active===false?'Return to AI':'Take over'}</button>}</div>}
 {detailsOnly&&ai.state?.currentSalesStage&&<details><summary>{ai.state.currentSalesStage.replaceAll('_',' ')} · {ai.state.paymentStatus||'Payment not verified'}</summary><p>{[ai.state.selectedService,ai.state.selectedPlatform,ai.state.duration&&`${ai.state.duration} days`,ai.state.quotedAmount&&`₦${Number(ai.state.quotedAmount).toLocaleString()}`,ai.state.invoiceId&&`Invoice: ${ai.state.invoiceId}`].filter(Boolean).join(' · ')}</p></details>}
 {detailsOnly&&session.actor.admin&&ai.state&&<details><summary>Correct sales details</summary><form onSubmit={e=>{e.preventDefault();action('state',{revision:conversation.revision,state:correction},'PUT');}}><label>Platform<select aria-label="Platform" value={correction.selectedPlatform??ai.state.selectedPlatform??''} onChange={e=>setCorrection({...correction,selectedPlatform:e.target.value})}><option value="">Unspecified</option><option value="tiktok">TikTok</option><option value="meta">Meta</option></select></label><label>Service<select aria-label="Service" value={correction.serviceType??ai.state.serviceType??''} onChange={e=>setCorrection({...correction,serviceType:e.target.value})}><option value="">Unspecified</option><option value="account_setup">Account setup</option><option value="ads_management">Ads management</option></select></label>{['budget','duration'].map(key=><label key={key}>{key}<input type="number" min="1" value={correction[key]??ai.state[key]??''} onChange={e=>setCorrection({...correction,[key]:Number(e.target.value)})}/></label>)}<button disabled={busy||!Object.keys(correction).length}>Save correction</button></form></details>}
 {!detailsOnly&&ai.assignmentError&&<p role="alert">{ai.assignmentError} {canControl&&<button disabled={busy} onClick={()=>action('control',{action:'retry_assignment'})}>Retry assignment</button>}</p>}
 {!detailsOnly&&draft&&draft.mode!=='LIVE'&&<section className={s.aiDraft}><b>AI suggested reply</b>{draft.action==='invoice'?<p>Generate an invoice for ₦{Number(draft.amount).toLocaleString()} using the configured payment details.</p>:editing?<textarea aria-label="Edit AI suggestion" value={text} onChange={e=>setText(e.target.value)} maxLength={4096}/>:<p>{draft.response}</p>}<footer><button disabled={busy||!canControl} onClick={()=>action('draft',{action:'send',...(editing?{text}:{})})}>{draft.action==='invoice'?'Generate & send invoice':'Send'}</button>{draft.action!=='invoice'&&<button disabled={busy||!canControl} onClick={()=>setEditing(!editing)}>{editing?'Cancel edit':'Edit & send'}</button>}<button disabled={busy||!canControl} onClick={()=>action('draft',{action:'dismiss'})}>Dismiss</button></footer></section>}
 </div>;
}
